### ISSUE TITLE
Remove '&' character from plugin.xml to solve problems with cordova 6.5.0 on OSX

### ISSUE THREAD

**Issue by henrychavez** [vkeepe/card.io#14]
When I updated my cordova version to 6.5.0 the compilation failed because this:
`Error: Invalid character in entity name`
to solved i have to remove the '&' from the plugin.xml
